# Generated by Django 2.2.12 on 2020-05-23 04:52

from django.db import migrations, models
import django.db.models.deletion
import versionfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_txt', models.CharField(max_length=20, verbose_name='Version Number')),
                ('version', versionfield.fields.VersionField(verbose_name='Version as Int')),
                ('version_link', models.URLField(verbose_name='Link to Version Release Notes')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_link', models.URLField(verbose_name='Link to Change Notes')),
                ('change_type', models.IntegerField(verbose_name='Change Type')),
                ('summary', models.CharField(max_length=100, verbose_name='Change Summary')),
                ('details_html', models.TextField(verbose_name='Change Details in HTML')),
                ('details_text', models.TextField(verbose_name='Change Details in Plain Text')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='django_change_list.ReleaseModel')),
            ],
        ),
    ]
