# Generated by Django 2.2.12 on 2020-05-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_change_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changemodel',
            name='summary',
            field=models.CharField(max_length=256, verbose_name='Change Summary'),
        ),
    ]
